### ISSUE TITLE
DoesOrganisationUnitExist is vegan

### ISSUE THREAD

**Issue by ErroneousGiant** [captainqwerty/ActiveDirectoryEasyAPI#15]
After a long pause, the system threw an unhandled exception when given "bacon" instead of a properly formatted distinguishedName for an OU. DoesOrganisationalUnitExist also returns true when presented a distinguishedName for a user.

AuditTasks - Line 15

System.Runtime.InteropServices.COMException: The server is not operational

**Comment by captainqwerty** [comment]
Renamed to DoesDistinguishedNameExist to get around the issue where you can put in a users DN.  Going to look into it throwing an error when giving a none DN style.  Could consider a regex.

**Comment by captainqwerty** [comment]
Erm... This nasty bastard might work:
^(?:(?<cn>CN=(?<name>[^,]*)),)?(?:(?<path>(?:(?:CN|OU)=[^,]+,?)+),)?(?<domain>(?:DC=[^,]+,?)+)$

**Comment by ErroneousGiant** [comment]
And thus begins CaptainQwerty/RegExEasyAPI

Sent from Workspace ONE Boxer

On 9 Mar 2019 09:44, Antony Bragg <notifications@github.com> wrote:

Erm... This nasty bastard might work:
^(?:(?CN=(?[^,]*)),)?(?:(?(?:(?:CN|OU)=[^,]+,?)+),)?(?(?:DC=[^,]+,?)+)$

**Comment by captainqwerty** [comment]
The regex did not work. Added a custom exception to say when its an invalid DN
